module.exports = Object.freeze({
    EMAIL_SUBJECT: 'Welcome, Email',
    EMAIL_SUBJECT_REJECT_LEAVE: 'Email for the Leave rejection reason',
    EMAIL_SUBJECT_APPROVE_LEAVE: 'Email for the Leave approved reason',
    EMAIL_SUBJECT_REGENERATE_PASSWORD: 'Email for the regenerate password',
    EMAIL_SUBJECT_DELETED_USER: "Account Deleted successfully",
    CREATED: 'Successfully created',
    MOBILE_EXIST: 'Mobile Already Exists',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    EMPLOYEE_LIST: 'Employee list are',
    EMAIL_IS_INVALID: 'Email invalid',
    PASSWORD_EMAIL_IS_INVALID: 'Please enter correct email or password',
    LOGIN_SUCCESS: 'Successfully login',
    Super_Admin: 'superAdmin',
    Default_role : "Employee as default role",
    TOKEN_REQUIRED: 'Login has been expired please try again',
    SUCCESSFULLY_UPDATE: 'Updated successfully ',
    DELETED_SUCCESSFULLY: 'Deleted successfully ',
    FILE_NOT_EXIST: 'File is not exist',
    ID_DOES_NOT_EXIST: 'Id does not exist',
    EMAIL_IS_ALREADY_EXIST: 'Email already exist',
    GEN_SALT_VALUE: '10',
    URL_EXPIRED: 'URL is no longer valid',
    UPLOAD_FILE_SIZE: 5000000,
    RECORD_LIST_SUCCESS: 'Fetch record successfully',
    RECORD_NOT_FOUND: 'Record not found',
    USER_NOT_FOUND: 'User not found',
    USER_DEL_SUCCESS: 'User deleted successfully',
    USER_CREATED_SUCCESS: 'User created successfully',
    RESET_PASSWORD_SUCCESS: 'Reset password successfully',
    EMAIL_IS_ALREADY: 'Email already exist',
    UNAUTHORIZED_LOGIN: 'Authorization required',
    USER_DETAIL_FETCH_SUCCESS: 'Details fetch successfully',
    LEAVES_REQ_SUCCESS: 'Request has been successful please wait for response',
    LEAVE_REQ_NOT_FOUND: 'Leave request not found',
    LEAVE_REQ_UPDATE_SUCCESS: 'Leave request status updated successfully',
    LEAVE_REQ_ALREADY_PROCEED: 'Leave request status already ',
    ROLE_ADDED_SUCCESSFUL: "Roles added successfully",
    ROLE_ADDED_EXIST: 'Role name already exist',
    SELFROLES_CANNOT_MODIFIED :"Own roles cannot be modified",
    ROLE_INVALID: 'Role Does not Found',
    ROLE_NOT_ALLOWED_TO_DELETE: 'This role is not allowed to delete',
    ROLE_NOT_ALLOWED_TO_EDIT: 'This role is not allowed to edit',
    ROLE_DELETED_SUCCESSFULLY: 'Role deleted successfully',
    ROLE_NOT_FOUND: 'Role not found',
    ROLE_INVALID: "Assign valid role",
    ROLE_UPDATED_SUCCESSFULLY: 'Successfully updated',
    ROLE_DATA_FETCH: 'Data successfully fetch',
    PERMISSION_UPDATE: 'Permission updated successfully',
    TOTAL_LEAVE_REQUEST: 'Total leave request are',
    TOTAL_USER: 'Total users are',
    TOTAL_ROLE: 'Total roles are',
    NOT_ACCESS: 'Unauthorized, do not have access',
    REQ_LEAVE_DETAILS: 'Successfully fetch leave request',
    BAD_REQUEST: 'Bad request',
    PERMISSION: 'please enter atleast one permission',
    ONLY_SUPER_ADMIN_ALLOWED: 'Only superadmin is allowed to add previous leave',
    LEAVE_CREATED_BY_SUPER_ADMIN: 'Leave created by superadmin',
    LEAVE_STATUS_DESCRIPTION: 'Please enter leaveStatusDescription',
    PSWD_CHANGE_SUCCESSFUL: 'Password updated successfully',
    PSWD_CHANGE_FAIl:"Incorrect old password",
    INCORRECT_OLDPASSWORD:  'Incorrect old password',
    NEW_PASSWORD:  'Password updated successfully',
    SAME_NEWPASSWORD_AND_OLDPASSWORD: 'New password should not be same as  old password',
    PSSWD_SHOULD_MATCH:'Both field should match',
    ALREADY_DELETED:"Already deleted",
    EMAIL_SUBJECT_BIRTH:"Wish you a happy birthday",
    FEEDBACK_SUBMITTED:"Feedback added successfully",
    FEEDBACK_UPDATED: "Feedback updated successfully",
    EXIST_NAME: 'Please choose differnt name',
    ORGANIZATION_UNIQUE_CODE: "Please provide organisation unique code to add Employee",
    USER_INACTIVE:"You are not authorized to log in please contact your admin",
    SECRET_KEY: "Please provide secret key",
    SECRET_KEY_INVALID: "Invalid secret key",
    LEAVE_STARTDATE_ENDDATE_ISSUE : "End date should not be less than start date"
  })

  